version: '3'
services:
  scrapping-python:
    build: ./scrapping/python
    container_name: scrapping-python
    environment:
      APP_ENV: "development"
      APP_DEBUG: "True"
      APP_PORT: 5000
      KABUM_PRODUCT_URL: "${KABUM_PRODUCT_URL}"
      USER_AGENT: "${USER_AGENT}"
    ports: 
        - 5000:5000
    volumes:
      - ./scrapping/python:/code

  projection-clojure:
    build: ./projection/clojure
    ports:
      - "7000:7000"
      #- "3000:3000"
      - "8080:8080"
    volumes:
      - ./projection/clojure:/code
      #- ~/.m2:/root/.m2
      #- ~/.lein:/root/.lein

  projection-clojure-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ~/.track-price/postgres/data:/var/lib/postgresql/data

  activemq:
    image: rmohr/activemq:latest
    #environment:
      #- "TZ=Europe/Amsterdam"
    #volumes:
      #- "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)

  camel:
    build: ./integration/camel
    #volumes:
      #- ./integration/camel/target/camel-0.0.1-SNAPSHOT.jar:/code/camel.jar
    ports:
      - "8090:8080"
